# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-26 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('collection', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2048, verbose_name='链接')),
                ('title', models.CharField(max_length=600, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('collection', models.ManyToManyField(to='collection.Collection', verbose_name='收藏集')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='创建者')),
                ('tag', models.ManyToManyField(to='tag.Tag', verbose_name='标签')),
            ],
            options={
                'db_table': 'bookmark',
            },
        ),
    ]
